# Generated by Django 4.1.4 on 2022-12-18 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("second", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="context",
            new_name="content",
        ),
    ]
